CREATE OR REPLACE TABLE "RETAIL_ANALYTICS"."CRM"."CUSTOMER" (
  "ID" NUMBER(38,0) NOT NULL,
  "EMAIL" VARCHAR(320) NOT NULL,
  "PROFILE" OBJECT,
  "PREFERENCES" OBJECT,
  "CREATED_AT" TIMESTAMP_NTZ NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE OR REPLACE TABLE "RETAIL_ANALYTICS"."SALES"."ORDER" (
  "ID" NUMBER(38,0) NOT NULL,
  "CUSTOMER_ID" NUMBER(38,0) NOT NULL,
  "TOTAL_AMOUNT" NUMBER(18,4) NOT NULL,
  "ITEMS" ARRAY,
  PRIMARY KEY ("ID")
);
