/* Demo schema — subscription tracking. Used when no real project is loaded.
   Ported from DataLex design prototype. */
export const DEMO_SCHEMA = {
  name: "Subscription Tracking",
  engine: "PostgreSQL 16",
  schema: "public",
  tables: [
    {
      id: "user", name: "user", schema: "public", cat: "users", subject: "Identity",
      x: 900, y: 80, badges: ["BASE"], rowCount: "12.4K",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "username", type: "varchar(50)", nn: true, unique: true },
        { name: "email", type: "varchar(255)", nn: true, unique: true, check: "email ~* '^.+@.+\\..+$'" },
        { name: "first_name", type: "varchar(100)", nn: true },
        { name: "last_name", type: "varchar(100)", nn: true },
        { name: "phone", type: "varchar(20)" },
        { name: "department_id", type: "integer", fk: "department.id", onDelete: "SET NULL" },
        { name: "role", type: "varchar(50)", nn: true, default: "'member'" },
        { name: "created_at", type: "timestamptz", nn: true, default: "now()", generated: false },
        { name: "last_login_at", type: "timestamptz" },
      ],
    },
    {
      id: "department", name: "department", schema: "public", cat: "users", subject: "Identity",
      x: 900, y: 450, badges: ["BASE"], rowCount: "42",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "name", type: "varchar(100)", nn: true, unique: true },
        { name: "description", type: "text" },
        { name: "manager_id", type: "integer", fk: "user.id", onDelete: "SET NULL" },
      ],
    },
    {
      id: "subscription", name: "subscription", schema: "public", cat: "billing", subject: "Billing",
      x: 80, y: 90, badges: ["BASE"], rowCount: "8.1K",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "software_id", type: "integer", fk: "software.id", nn: true, onDelete: "RESTRICT" },
        { name: "user_id", type: "integer", fk: "user.id", nn: true, onDelete: "CASCADE" },
        { name: "start_date", type: "date", nn: true },
        { name: "end_date", type: "date", nn: true, check: "end_date >= start_date" },
        { name: "renewal_date", type: "date" },
        { name: "auto_renewal", type: "boolean", nn: true, default: "false" },
        { name: "status", type: "varchar(30)", nn: true, default: "'active'" },
        { name: "cost", type: "numeric(12,2)", nn: true, check: "cost >= 0" },
        { name: "currency", type: "currency_enum", nn: true, default: "'USD'" },
        { name: "license_key", type: "varchar(255)" },
        { name: "seats", type: "integer", nn: true, default: "1" },
        { name: "payment_method", type: "varchar(50)" },
      ],
    },
    {
      id: "payment", name: "payment", schema: "public", cat: "billing", subject: "Billing",
      x: 460, y: 130, badges: ["BASE"], rowCount: "34.8K",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "subscription_id", type: "integer", fk: "subscription.id", nn: true, onDelete: "CASCADE" },
        { name: "payment_date", type: "date", nn: true, default: "now()" },
        { name: "amount", type: "numeric(12,2)", nn: true, check: "amount > 0" },
        { name: "currency", type: "currency_enum", nn: true },
        { name: "payment_method", type: "varchar(50)", nn: true },
        { name: "invoice_number", type: "varchar(100)", unique: true },
        { name: "paid_by", type: "integer", fk: "user.id", onDelete: "SET NULL" },
        { name: "notes", type: "text" },
      ],
    },
    {
      id: "software", name: "software", schema: "public", cat: "product", subject: "Product",
      x: 80, y: 570, badges: ["BASE"], rowCount: "284",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "name", type: "varchar(255)", nn: true },
        { name: "version", type: "varchar(50)" },
        { name: "vendor_id", type: "integer", fk: "vendor.id", nn: true, onDelete: "RESTRICT" },
        { name: "description", type: "text" },
        { name: "website", type: "varchar(255)" },
        { name: "category", type: "varchar(100)" },
      ],
    },
    {
      id: "software_tag", name: "software_tag", schema: "public", cat: "product", subject: "Product",
      x: 460, y: 570, badges: ["JUNCTION"], rowCount: "1.2K", junction: true,
      columns: [
        { name: "software_id", type: "integer", pk: true, fk: "software.id", nn: true, onDelete: "CASCADE" },
        { name: "tag_id", type: "integer", pk: true, fk: "tag.id", nn: true, onDelete: "CASCADE" },
        { name: "tagged_at", type: "timestamptz", nn: true, default: "now()" },
        { name: "tagged_by", type: "integer", fk: "user.id", onDelete: "SET NULL" },
      ],
    },
    {
      id: "tag", name: "tag", schema: "public", cat: "product", subject: "Product",
      x: 780, y: 620, badges: ["BASE"], rowCount: "58",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "name", type: "varchar(50)", nn: true, unique: true },
        { name: "color", type: "varchar(7)" },
      ],
    },
    {
      id: "vendor", name: "vendor", schema: "public", cat: "product", subject: "Product",
      x: 80, y: 890, badges: ["BASE"], rowCount: "67",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "name", type: "varchar(255)", nn: true, unique: true },
        { name: "website", type: "varchar(255)" },
        { name: "contact_email", type: "varchar(255)" },
        { name: "contact_phone", type: "varchar(50)" },
        { name: "address", type: "jsonb" },
        { name: "support_url", type: "varchar(255)" },
      ],
    },
    {
      id: "audit_log", name: "audit_log", schema: "public", cat: "audit", subject: "Audit",
      x: 1320, y: 590, badges: ["BASE", "PART"], rowCount: "1.2M",
      columns: [
        { name: "id", type: "bigserial", pk: true, nn: true },
        { name: "actor_id", type: "integer", fk: "user.id", onDelete: "SET NULL" },
        { name: "action", type: "varchar(50)", nn: true },
        { name: "entity_type", type: "varchar(50)", nn: true },
        { name: "entity_id", type: "integer", nn: true },
        { name: "diff", type: "jsonb" },
        { name: "created_at", type: "timestamptz", nn: true, default: "now()" },
      ],
    },
    {
      id: "permission", name: "permission", schema: "public", cat: "access", subject: "Access",
      x: 1320, y: 90, badges: ["BASE"], rowCount: "156",
      columns: [
        { name: "id", type: "serial", pk: true, nn: true },
        { name: "user_id", type: "integer", fk: "user.id", nn: true, onDelete: "CASCADE" },
        { name: "resource", type: "varchar(100)", nn: true },
        { name: "level", type: "varchar(30)", nn: true, check: "level IN ('read','write','admin')" },
        { name: "granted_at", type: "timestamptz", nn: true, default: "now()" },
        { name: "expires_at", type: "timestamptz" },
      ],
    },
    {
      id: "user_profile", name: "user_profile", schema: "public", cat: "users", subject: "Identity",
      x: 1320, y: 350, badges: ["BASE"], rowCount: "12.4K",
      columns: [
        { name: "user_id", type: "integer", pk: true, fk: "user.id", nn: true, onDelete: "CASCADE" },
        { name: "avatar_url", type: "varchar(255)" },
        { name: "bio", type: "text" },
        { name: "locale", type: "varchar(10)", default: "'en-US'" },
        { name: "timezone", type: "varchar(50)" },
      ],
    },
    {
      id: "currency_enum", name: "currency_enum", schema: "public", cat: "system", subject: "System",
      kind: "ENUM", x: 460, y: 650, badges: ["ENUM"], rowCount: "8 values",
      columns: [
        { name: "USD", type: "enum value" },
        { name: "EUR", type: "enum value" },
        { name: "GBP", type: "enum value" },
        { name: "JPY", type: "enum value" },
        { name: "INR", type: "enum value" },
      ],
    },
  ],
  relationships: [
    { id: "r1", name: "fk_subscription_user",
      from: { table: "subscription", col: "user_id", side: "right", min: "1", max: "N" },
      to:   { table: "user", col: "id", side: "left", min: "1", max: "1" },
      identifying: false, onDelete: "CASCADE", onUpdate: "NO ACTION" },
    { id: "r2", name: "fk_subscription_software",
      from: { table: "subscription", col: "software_id", side: "left", min: "1", max: "N" },
      to:   { table: "software", col: "id", side: "right", min: "1", max: "1" },
      identifying: false, onDelete: "RESTRICT", onUpdate: "NO ACTION" },
    { id: "r3", name: "fk_payment_subscription",
      from: { table: "payment", col: "subscription_id", side: "left", min: "1", max: "N" },
      to:   { table: "subscription", col: "id", side: "right", min: "1", max: "1" },
      identifying: true, onDelete: "CASCADE", onUpdate: "NO ACTION" },
    { id: "r4", name: "fk_payment_paid_by",
      from: { table: "payment", col: "paid_by", side: "right", min: "0", max: "N" },
      to:   { table: "user", col: "id", side: "left", min: "0", max: "1" },
      identifying: false, dashed: true, onDelete: "SET NULL", onUpdate: "NO ACTION" },
    { id: "r5", name: "fk_software_vendor",
      from: { table: "software", col: "vendor_id", side: "bottom", min: "1", max: "N" },
      to:   { table: "vendor", col: "id", side: "top", min: "1", max: "1" },
      identifying: false, onDelete: "RESTRICT", onUpdate: "NO ACTION" },
    { id: "r6", name: "fk_user_department",
      from: { table: "user", col: "department_id", side: "bottom", min: "0", max: "N" },
      to:   { table: "department", col: "id", side: "top", min: "0", max: "1" },
      identifying: false, dashed: true, onDelete: "SET NULL", onUpdate: "NO ACTION" },
    { id: "r7", name: "fk_department_manager",
      from: { table: "department", col: "manager_id", side: "left", min: "0", max: "1" },
      to:   { table: "user", col: "id", side: "left", min: "0", max: "1" },
      identifying: false, dashed: true, onDelete: "SET NULL", onUpdate: "NO ACTION" },
    { id: "r8", name: "fk_audit_actor",
      from: { table: "audit_log", col: "actor_id", side: "top", min: "0", max: "N" },
      to:   { table: "user", col: "id", side: "right", min: "0", max: "1" },
      identifying: false, dashed: true, onDelete: "SET NULL", onUpdate: "NO ACTION" },
    { id: "r9", name: "fk_permission_user",
      from: { table: "permission", col: "user_id", side: "left", min: "1", max: "N" },
      to:   { table: "user", col: "id", side: "right", min: "1", max: "1" },
      identifying: false, onDelete: "CASCADE", onUpdate: "NO ACTION" },
    { id: "r10", name: "enum_subscription_currency",
      from: { table: "subscription", col: "currency", side: "right", min: "1", max: "N" },
      to:   { table: "currency_enum", col: "USD", side: "left", min: "1", max: "1" },
      identifying: false, dashed: true, enumRef: true },
    { id: "r11", name: "enum_payment_currency",
      from: { table: "payment", col: "currency", side: "bottom", min: "1", max: "N" },
      to:   { table: "currency_enum", col: "USD", side: "top", min: "1", max: "1" },
      identifying: false, dashed: true, enumRef: true },
    { id: "r12", name: "fk_profile_user",
      from: { table: "user_profile", col: "user_id", side: "left", min: "0", max: "1" },
      to:   { table: "user", col: "id", side: "right", min: "1", max: "1" },
      identifying: true, onDelete: "CASCADE", onUpdate: "NO ACTION" },
    { id: "r13", name: "jx_softag_software",
      from: { table: "software_tag", col: "software_id", side: "left", min: "0", max: "N" },
      to:   { table: "software", col: "id", side: "right", min: "1", max: "1" },
      identifying: true, onDelete: "CASCADE", onUpdate: "NO ACTION" },
    { id: "r14", name: "jx_softag_tag",
      from: { table: "software_tag", col: "tag_id", side: "right", min: "0", max: "N" },
      to:   { table: "tag", col: "id", side: "left", min: "1", max: "1" },
      identifying: true, onDelete: "CASCADE", onUpdate: "NO ACTION" },
  ],
  derivedManyToMany: [
    { id: "mn1", a: "software", b: "tag", via: "software_tag" },
  ],
  subjectAreas: [
    { id: "sa-identity", label: "Identity & Access", cat: "users",   x: 870, y: 50,  w: 580, h: 640 },
    { id: "sa-billing",  label: "Billing",           cat: "billing", x: 50,  y: 60,  w: 780, h: 470 },
    { id: "sa-product",  label: "Product Catalog",   cat: "product", x: 50,  y: 545, w: 840, h: 460 },
    { id: "sa-audit",    label: "Audit",             cat: "audit",   x: 1290, y: 565, w: 330, h: 200 },
  ],
};
